#Project Data Siswa
Sampel 1000 data Siswa, beragam memiliki 10 kolom

Usia : 16 - 18
Gender : L/P
Jurusan : IPA, IPS, BI
Asal Sekolah : SMP 1, SMP 2, SMP 3
Semester : 1, 2
Kelas : 10, 11, 12
Mata Pelajaran : Matematika, Bahasa Indonesia, Bahasa Inggris
Absen : Hadir, Izin, Sakit, Alfa
KKM  : 75, 80, 90
Kategori : Beasiswa, NonBeasiswa

In [72]:
import numpy as np
import pandas as pd

n_data = 1000

usia = np.random.randint(18,23,size=n_data)
gender = np.random.choice(['L','P'],size=n_data)
jurusan = np.random.choice(['IPA','IPS','BI'],size=n_data)
asalSekolah = np.random.choice(['SMP1','SMP2','SMP3'],size=n_data)
semester = np.random.randint(1,2,size=n_data)
kelas = np.random.choice(['10','11','12'],size=n_data)
mapel = np.random.choice(['MTK','Bahasa Indonesia','Bahasa Inggris'],size=n_data)
absen = np.random.choice(['Hadir','Izin','Sakit','Alfa'],size=n_data)
kkm = np.random.randint(75,80,size=n_data)
kategori = np.random.choice(['Beasiswa','Non Beasiswa'],size=n_data)

df = pd.DataFrame({
    'Usia' : usia,
    'Gender' : gender,
    'Jurusan' : jurusan,
    'Asal Sekolah' : asalSekolah,
    'Semester' : semester,
    'Kelas' : kelas,
    'Mata Pelajaran' : mapel,
    'Absen' : absen,
    'kkm' : kkm,
    'Kategori' : kategori
})

print(df.info)
print(f"Usia siswa termuda: {df.Usia.min()}")
print(f"Usia siswa tertua: {df.Usia.max()}")
jmlL = df[df['Gender']=='L']
jmlP = df[df['Gender']=='P']
print(f"Jumlah mahasiswa laki-laki: {jmlL.size/10}")
print(f"Jumlah mahasiswa perempuan: {jmlP.size/10}")
jmlIPA = df[df['Jurusan']=='IPA']
jmlIPS = df[df['Jurusan']=='IPS']
jmlBI = df[df['Jurusan']=='BI']
print(f"Jumlah siswa jurusan IPA: {jmlIPA.size/10}")
print(f"Jumlah siswa jurusan IPS: {jmlIPS.size/10}")
print(f"Jumlah siswa jurusan BI: {jmlBI.size/10}")
jmlSMP1 = df[df['Asal Sekolah']=='SMP1']
jmlSMP2 = df[df['Asal Sekolah']=='SMP2']
jmlSMP3 = df[df['Asal Sekolah']=='SMP3']
print(f"Jumlah asal sekolah SMP1: {jmlSMP1.size/10}")
print(f"Jumlah asal sekolah SMP2: {jmlSMP2.size/10}")
print(f"Jumlah asal sekolah SMP3: {jmlSMP3.size/10}")
smstrDua = df[df['Semester']>=2]
print(f"Jumlah mahasiswa semester Dua: {smstrDua.size}")
sepuluh = df[df['Kelas']=='10']
sebelas = df[df['Kelas']=='11']
duabelas= df[df['Kelas']=='12']
print(f"Jumlah siswa kelas reguler: {sepuluh.size/10}")
print(f"Jumlah siswa kelas sebelas: {sebelas.size/10}")
print(f"Jumlah siswa kelas duabelas: {duabelas.size/10}")
mtk = df[df['Mata Pelajaran']=='MTK']
print(f"Jumlah siswa yang belajar matematika: {mtk.size/10}")
absen = df[df['Absen']=='Hadir']
print(f"Jumlah absen yang hadir dikelas: {absen.size/10}")
print(f"Rata-rata kkm: {df.kkm.mean()}")
bea = df[df['Kategori']=='Beasiswa']
non = df[df['Kategori']=='Non Beasiswa']
print(f"Jumlah siswa beasiswa: {bea.size/10}")
print(f"Jumlah siswa non-beasiswa: {non.size/10}")

df.to_csv('dataSiswa.CSV')

<bound method DataFrame.info of      Usia Gender Jurusan Asal Sekolah  Semester Kelas    Mata Pelajaran  \
0      18      P      BI         SMP3         1    12               MTK
1      20      P      BI         SMP2         1    10    Bahasa Inggris
2      21      L     IPA         SMP3         1    11               MTK
3      18      L     IPS         SMP2         1    12               MTK
4      19      P     IPA         SMP2         1    12  Bahasa Indonesia
..    ...    ...     ...          ...       ...   ...               ...
995    18      P     IPS         SMP2         1    10    Bahasa Inggris
996    18      L     IPS         SMP1         1    11  Bahasa Indonesia
997    18      L     IPA         SMP1         1    11  Bahasa Indonesia
998    22      P     IPS         SMP3         1    11  Bahasa Indonesia
999    21      P     IPA         SMP3         1    10    Bahasa Inggris

     Absen  kkm      Kategori
0    Hadir   78      Beasiswa
1     Izin   76  Non Beasiswa
2     Izin   79  Non Beasiswa
3    Hadir   78  Non Beasiswa
4     Alfa   76  Non Beasiswa
..     ...  ...           ...
995   Alfa   75      Beasiswa
996   Izin   75  Non Beasiswa
997   Alfa   77  Non Beasiswa
998  Hadir   78      Beasiswa
999  Sakit   79      Beasiswa

[1000 rows x 10 columns]>
Usia siswa termuda: 18
Usia siswa tertua: 22
Jumlah mahasiswa laki-laki: 490.0
Jumlah mahasiswa perempuan: 510.0
Jumlah siswa jurusan IPA: 339.0
Jumlah siswa jurusan IPS: 322.0
Jumlah siswa jurusan BI: 339.0
Jumlah asal sekolah SMP1: 339.0
Jumlah asal sekolah SMP2: 342.0
Jumlah asal sekolah SMP3: 319.0
Jumlah mahasiswa semester Dua: 0
Jumlah siswa kelas reguler: 302.0
Jumlah siswa kelas sebelas: 341.0
Jumlah siswa kelas duabelas: 357.0
Jumlah siswa yang belajar matematika: 333.0
Jumlah absen yang hadir dikelas: 238.0
Rata-rata kkm: 76.973
Jumlah siswa beasiswa: 497.0
Jumlah siswa non-beasiswa: 503.0