In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
df = pd.read_csv('demographic.csv')
df

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,Toy Story,Animation; Comedy; Family,81.0,7.7,5415.0,1995,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,Jumanji,Adventure; Fantasy; Family,104.0,6.9,2413.0,1995,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Grumpier Old Men,Romance; Comedy,101.0,6.5,92.0,1995,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
3,Waiting to Exhale,Comedy; Drama; Romance,127.0,6.1,34.0,1995,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,Father of the Bride Part II,Comedy,106.0,5.7,173.0,1995,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45125,Robin Hood,Drama; Action; Romance,104.0,5.7,26.0,1991,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
45126,Century of Birthing,Drama,360.0,9.0,3.0,2011,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45127,Betrayal,Action; Drama; Thriller,90.0,3.8,6.0,2003,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
45128,Satan Triumphant,NaN,87.0,0.0,0.0,1917,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45129,Queerama,NaN,75.0,0.0,0.0,2017,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
Berikut kesimpulan singkat dari dataset film:

Dataset mencakup 45.130 film dari tahun 1917 hingga 2017.

Genre paling umum: Comedy, Drama, Action, dan Romance.

Banyak film memiliki lebih dari satu genre.

Durasi film umumnya antara 75â€“120 menit.

Sebagian besar film memiliki rating antara 5â€“8.

Beberapa data genre masih hilang (NaN).